### ISSUE TITLE
Support needed for inversions

### ISSUE THREAD

**Issue by glennhickey** [jmonlong/sveval#1]
I don't think this should be too hard to add, as it seems like they should be comparable in the same way as deletions.  

 In vg, we're outputting inversions as multibase snps and then comparing to symbolic allele <INV>'s so it would be ideal to compare transparently between these.  If that's not doable, just supporting one or the other (<INV> or multibase SNP) would be fine too, and the VCF's can get fixed up as a preprocessing step.

**Comment by jmonlong** [comment]
Sounds good, I'll give it a try. Symbolic allele will be easy. For the multibase way I guess we'll have to check if the ALT is more or less reverse complement than REF, right? There could be other multibase snps in vg output that are not inversions?

Also in term of size, I guess both REF and ALT will not necessarily have exactly the same size in vg output for an inversion?

**Comment by glennhickey** [comment]
For the vg output on the SV construct graph with --recall, all multibase
snps will be inversions.   But that's a pretty specific case.  In general I
think we'd need to allow some minor variation (snps and/or indels) like you
say.

**Comment by jmonlong** [comment]
I added inversions. When REF/ALT sequences are provided I picked 80% match when aligning REF and the reverse complement of ALT as a rule to classify a variant as INV. Otherwise it's INS or DEL depending on which REF/ALT is larger.

I made it a release so that the docker image is easier to update in toil-vg. It's now `jmonlong/sveval:version-1.0.0`
